name: erro-sync

on:
  repository_dispatch:
    types: [erro-sync]

permissions:
  actions: read
  attestations: none
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: write
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: write

env:
  submodule_path: ".local/share/unciae"

jobs:
  erro-sync:
    uses: streambinder/streambinder/.github/workflows/push.yml@master
