name: erro-sync

on:
  repository_dispatch:
    types: [erro-sync]

permissions: read-all

env:
  submodule_path: ".local/share/unciae"

jobs:
  erro-sync:
    uses: streambinder/streambinder/.github/workflows/push.yml@master
    secrets:
      GH_ACTIONS_DAVIDEPUCCI: ${{ secrets.GH_ACTIONS_DAVIDEPUCCI }}
